//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dr.finder_project.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment_tbl
    {
        public decimal Appointment_Id { get; set; }
        public Nullable<decimal> Hospital_Id { get; set; }
        public Nullable<decimal> User_S_Id { get; set; }
        public string Appointment_Date { get; set; }
        public string Appointment_Current_Date { get; set; }
        public string Appointment_Description { get; set; }
        public string Appointment_Status { get; set; }
    }
}
