//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dr.finder_project.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Certificate_tbl
    {
        public decimal Certificate_Id { get; set; }
        public Nullable<decimal> Doctor_Id { get; set; }
        public string Certificate_Image { get; set; }
        public string Certificate_Details { get; set; }
    }
}
