//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dr.finder_project.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doctor_Type_tbl
    {
        public decimal Doctor_Type_Id { get; set; }
        public string Doctor_Type_Name { get; set; }
    }
}
