//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dr.finder_project.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doctor_tbl
    {
        public decimal Doctor_Id { get; set; }
        public string Doctor_fname { get; set; }
        public string Doctor_mname { get; set; }
        public string Doctor_lname { get; set; }
        public string Doctor_Image { get; set; }
        public Nullable<decimal> Doctor_Mobile_No { get; set; }
        public Nullable<decimal> Hospital_Id { get; set; }
        public Nullable<decimal> Doctor_Type_Id { get; set; }
        public string Doctor_gender { get; set; }
        public string Doctor_Email_Id { get; set; }
        public string Doctor_password { get; set; }
        public string Doctor_Status { get; set; }
        public string Doctor_Experience { get; set; }
        public string Doctor_Address { get; set; }
        public string Doctor_reg_date { get; set; }
        public string Doctor_city { get; set; }
    }
}
