//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dr.finder_project.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facility_tbl
    {
        public decimal Facility_Id { get; set; }
        public string Facility_Name { get; set; }
        public Nullable<decimal> Hospital_Id { get; set; }
        public string Facility_Description { get; set; }
    }
}
