//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dr.finder_project.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hospital_tbl
    {
        public decimal Hospital_Id { get; set; }
        public string Hospital_Name { get; set; }
        public string Hospital_Image { get; set; }
        public Nullable<decimal> Hospital_Mobile_No { get; set; }
        public string Hospital_Email_Id { get; set; }
        public string Hospital_Address { get; set; }
        public string Hospital_Discription { get; set; }
        public string Hospital_Status { get; set; }
        public string Hospital_password { get; set; }
        public string Hospital_reg_date { get; set; }
        public string Hospital_city { get; set; }
    }
}
