//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dr.finder_project.EDM
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class Dr_finderEntities3 : DbContext
    {
        public Dr_finderEntities3()
            : base("name=Dr_finderEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Appointment_tbl> Appointment_tbl { get; set; }
        public DbSet<Assign_tbl> Assign_tbl { get; set; }
        public DbSet<Certificate_tbl> Certificate_tbl { get; set; }
        public DbSet<Doctor_tbl> Doctor_tbl { get; set; }
        public DbSet<Doctor_Type_tbl> Doctor_Type_tbl { get; set; }
        public DbSet<Facility_tbl> Facility_tbl { get; set; }
        public DbSet<Hospital_tbl> Hospital_tbl { get; set; }
        public DbSet<Review_tbl> Review_tbl { get; set; }
        public DbSet<User_s_tbl> User_s_tbl { get; set; }
    
        public virtual ObjectResult<app_chk_st_Result> app_chk_st(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<app_chk_st_Result>("app_chk_st", idParameter);
        }
    
        public virtual int Book_app(string qpp_date, string qpp_cur_date, Nullable<decimal> hos_id, Nullable<decimal> u_id, string qpp_desc, string qpp_status)
        {
            var qpp_dateParameter = qpp_date != null ?
                new ObjectParameter("qpp_date", qpp_date) :
                new ObjectParameter("qpp_date", typeof(string));
    
            var qpp_cur_dateParameter = qpp_cur_date != null ?
                new ObjectParameter("qpp_cur_date", qpp_cur_date) :
                new ObjectParameter("qpp_cur_date", typeof(string));
    
            var hos_idParameter = hos_id.HasValue ?
                new ObjectParameter("hos_id", hos_id) :
                new ObjectParameter("hos_id", typeof(decimal));
    
            var u_idParameter = u_id.HasValue ?
                new ObjectParameter("u_id", u_id) :
                new ObjectParameter("u_id", typeof(decimal));
    
            var qpp_descParameter = qpp_desc != null ?
                new ObjectParameter("qpp_desc", qpp_desc) :
                new ObjectParameter("qpp_desc", typeof(string));
    
            var qpp_statusParameter = qpp_status != null ?
                new ObjectParameter("qpp_status", qpp_status) :
                new ObjectParameter("qpp_status", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Book_app", qpp_dateParameter, qpp_cur_dateParameter, hos_idParameter, u_idParameter, qpp_descParameter, qpp_statusParameter);
        }
    
        public virtual int insassign(Nullable<int> aid, Nullable<int> uid, Nullable<int> hid, Nullable<int> drid)
        {
            var aidParameter = aid.HasValue ?
                new ObjectParameter("aid", aid) :
                new ObjectParameter("aid", typeof(int));
    
            var uidParameter = uid.HasValue ?
                new ObjectParameter("uid", uid) :
                new ObjectParameter("uid", typeof(int));
    
            var hidParameter = hid.HasValue ?
                new ObjectParameter("hid", hid) :
                new ObjectParameter("hid", typeof(int));
    
            var dridParameter = drid.HasValue ?
                new ObjectParameter("drid", drid) :
                new ObjectParameter("drid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insassign", aidParameter, uidParameter, hidParameter, dridParameter);
        }
    
        public virtual ObjectResult<tbldrview_Result> tbldrview(Nullable<int> id, string st)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var stParameter = st != null ?
                new ObjectParameter("st", st) :
                new ObjectParameter("st", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<tbldrview_Result>("tbldrview", idParameter, stParameter);
        }
    
        public virtual int upapp(Nullable<int> ch, Nullable<int> id, string status)
        {
            var chParameter = ch.HasValue ?
                new ObjectParameter("ch", ch) :
                new ObjectParameter("ch", typeof(int));
    
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var statusParameter = status != null ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("upapp", chParameter, idParameter, statusParameter);
        }
    
        public virtual ObjectResult<viewapp_Result> viewapp(Nullable<int> ch, Nullable<int> hid, string status)
        {
            var chParameter = ch.HasValue ?
                new ObjectParameter("ch", ch) :
                new ObjectParameter("ch", typeof(int));
    
            var hidParameter = hid.HasValue ?
                new ObjectParameter("hid", hid) :
                new ObjectParameter("hid", typeof(int));
    
            var statusParameter = status != null ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<viewapp_Result>("viewapp", chParameter, hidParameter, statusParameter);
        }
    
        public virtual ObjectResult<viewdrasapp_Result> viewdrasapp(Nullable<int> drid, string status)
        {
            var dridParameter = drid.HasValue ?
                new ObjectParameter("drid", drid) :
                new ObjectParameter("drid", typeof(int));
    
            var statusParameter = status != null ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<viewdrasapp_Result>("viewdrasapp", dridParameter, statusParameter);
        }
    }
}
