//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dr.finder_project.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review_tbl
    {
        public decimal Review_Id { get; set; }
        public string Review_Description { get; set; }
        public Nullable<int> No_Of_Rating { get; set; }
        public Nullable<System.DateTime> Review_Date { get; set; }
        public Nullable<decimal> User_S_Id { get; set; }
        public Nullable<decimal> Hospital_Id { get; set; }
        public Nullable<decimal> Doctor_Id { get; set; }
    }
}
