//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dr.finder_project.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_s_tbl
    {
        public decimal User_S_Id { get; set; }
        public string User_S_fName { get; set; }
        public string User_S_mName { get; set; }
        public string User_s_lName { get; set; }
        public string User_S_Email_Id { get; set; }
        public string User_S_Password { get; set; }
        public Nullable<decimal> User_S_Mobile_No { get; set; }
        public string User_S_Gender { get; set; }
        public string User_S_Address { get; set; }
        public Nullable<decimal> User_S_Pincode { get; set; }
        public string User_S_DOB { get; set; }
        public string User_S_City { get; set; }
        public string User_reg_date { get; set; }
        public string status { get; set; }
    }
}
